// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnsP8PZX6O7-sb7a7B1jHeLOPZZDTxUX4',
    appId: '1:973856710316:web:4ceca729fc6af117cec909',
    messagingSenderId: '973856710316',
    projectId: 'gada-two',
    authDomain: 'gada-two.firebaseapp.com',
    storageBucket: 'gada-two.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRb_doVsnsJ9UdhYU3v6m8WYMJxlSYd7g',
    appId: '1:973856710316:android:d917c22309747061cec909',
    messagingSenderId: '973856710316',
    projectId: 'gada-two',
    storageBucket: 'gada-two.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsdjbONoV9PVjnuXGIioKM7ytY4gy3dkU',
    appId: '1:973856710316:ios:6cc65464dfb1c950cec909',
    messagingSenderId: '973856710316',
    projectId: 'gada-two',
    storageBucket: 'gada-two.firebasestorage.app',
    iosBundleId: 'com.example.gadaTwo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsdjbONoV9PVjnuXGIioKM7ytY4gy3dkU',
    appId: '1:973856710316:ios:6cc65464dfb1c950cec909',
    messagingSenderId: '973856710316',
    projectId: 'gada-two',
    storageBucket: 'gada-two.firebasestorage.app',
    iosBundleId: 'com.example.gadaTwo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnsP8PZX6O7-sb7a7B1jHeLOPZZDTxUX4',
    appId: '1:973856710316:web:9a031eac9632fb1fcec909',
    messagingSenderId: '973856710316',
    projectId: 'gada-two',
    authDomain: 'gada-two.firebaseapp.com',
    storageBucket: 'gada-two.firebasestorage.app',
  );
}
